/*!
 * g.Raphael 0.5 - Charting library, based on Raphaël
 *
 * Copyright (c) 2009 Dmitry Baranovskiy (http://g.raphaeljs.com)
 * Copyright (c) 2011 Karol Kowalski
 * Licensed under the MIT (http://www.opensource.org/licenses/mit-license.php) license.
 */
Raphael.fn.g.fn.barchart=function(v,x,q,u,g,j){var j=j||{},k=this.paper,z={round:"round",sharp:"sharp",soft:"soft"}[j.type]||"square",m=parseFloat(j.gutter||"20%"),e=k.set(),r=k.set(),l=k.set(),i=k.set(),t=Math.max.apply(Math,g),c=[],h=0,A=j.colors||this.colors,n=g.length;if(k.raphael.is(g[0],"array")){for(var t=[],h=n,n=0,a=g.length;a--;)r.push(k.set()),t.push(Math.max.apply(Math,g[a])),n=Math.max(n,g[a].length);if(j.stacked)for(a=n;a--;){for(var p=0,b=g.length;b--;)p+=+g[b][a]||0;c.push(p)}for(a=
g.length;a--;)if(g[a].length<n)for(b=n;b--;)g[a].push(0);t=Math.max.apply(Math,j.stacked?c:t)}var t=j.to||t,q=q/(n*(100+m)+m)*100,m=q*m/100,o=j.vgutter==null?20:j.vgutter,c=[],p=v+m,s=(u-2*o)/t;j.stretch||(m=Math.round(m),q=Math.floor(q));!j.stacked&&(q/=h||1);for(a=0;a<n;a++){c=[];for(b=0;b<(h||1);b++){var d=Math.round((h?g[b][a]:g[a])*s),w=x+u-o-d,f=this.finger(Math.round(p+q/2),w+d,q,d,true,z).attr({stroke:"none",fill:A[h?b:a]});h?r[b].push(f):r.push(f);f.y=w;f.x=Math.round(p+q/2);f.w=q;f.h=d;
f.value=h?g[b][a]:g[a];j.stacked?c.push(f):p+=q}if(j.stacked){i.push(b=k.rect(c[0].x-c[0].w/2,x,q,u).attr(this.shim));b.bars=k.set();for(var w=0,y=c.length;y--;)c[y].toFront();for(var y=0,B=c.length;y<B;y++){var f=c[y],d=(w+f.value)*s,C=this.finger(f.x,x+u-o-!!w*0.5,q,d,true,z,1);b.bars.push(f);w&&f.attr({path:C});f.h=d;f.y=x+u-o-!!w*0.5-d;l.push(d=k.rect(f.x-f.w/2,f.y,q,f.value*s).attr(this.shim));d.bar=f;d.value=f.value;w+=f.value}p+=q}p+=m}i.toFront();p=v+m;if(!j.stacked)for(a=0;a<n;a++){for(b=
0;b<(h||1);b++)l.push(d=k.rect(Math.round(p),x+o,q,u-o).attr(this.shim)),d.bar=h?r[b][a]:r[a],d.value=d.bar.value,p+=q;p+=m}e.label=function(a,d){a=a||[];this.labels=k.set();var b,f=-Infinity;if(j.stacked)for(var c=0;c<n;c++)for(var m=0,e=0;e<(h||1);e++){if(m+=h?g[e][c]:g[c],e==h-1){b=k.g.labelise(a[c],m,t);b=k.g.text(r[c*(h||1)+e].x,x+u-o/2,b).insertBefore(l[c*(h||1)+e]);var i=b.getBBox();i.x-7<f?b.remove():(this.labels.push(b),f=i.x+i.width)}}else for(c=0;c<n;c++)for(e=0;e<(h||1);e++)b=k.g.labelise(h?
a[e]&&a[e][c]:a[c],h?g[e][c]:g[c],t),b=k.g.text(r[c*(h||1)+e].x,d?x+u-o/2:r[c*(h||1)+e].y-10,b).insertBefore(l[c*(h||1)+e]),i=b.getBBox(),i.x-7<f?b.remove():(this.labels.push(b),f=i.x+i.width);return this};e.hover=function(a,b){i.hide();l.show();l.mouseover(a).mouseout(b);return this};e.hoverColumn=function(a,b){l.hide();i.show();i.mouseover(a).mouseout(b||function(){});return this};e.click=function(a){i.hide();l.show();l.click(a);return this};e.each=function(a){if(!Raphael.is(a,"function"))return this;
for(var b=l.length;b--;)a.call(l[b]);return this};e.eachColumn=function(a){if(!Raphael.is(a,"function"))return this;for(var b=i.length;b--;)a.call(i[b]);return this};e.clickColumn=function(a){l.hide();i.show();i.click(a);return this};e.push(r,l,i);e.bars=r;e.covers=l;return e};
Raphael.fn.g.fn.hbarchart=function(v,x,q,u,g,j){var j=j||{},k=this.paper,z={round:"round",sharp:"sharp",soft:"soft"}[j.type]||"square",m=parseFloat(j.gutter||"20%"),e=k.set(),r=k.set(),l=k.set(),i=k.set(),t=Math.max.apply(Math,g),c=[],h=0,A=j.colors||this.colors,n=g.length;if(k.raphael.is(g[0],"array")){for(var t=[],h=n,n=0,a=g.length;a--;)r.push(k.set()),t.push(Math.max.apply(Math,g[a])),n=Math.max(n,g[a].length);if(j.stacked)for(a=n;a--;){for(var p=0,b=g.length;b--;)p+=+g[b][a]||0;c.push(p)}for(a=
g.length;a--;)if(g[a].length<n)for(b=n;b--;)g[a].push(0);t=Math.max.apply(Math,j.stacked?c:t)}var t=j.to||t,o=Math.floor(u/(n*(100+m)+m)*100),u=Math.floor(o*m/100),m=[],c=x+u,p=(q-1)/t;!j.stacked&&(o/=h||1);for(a=0;a<n;a++){m=[];for(b=0;b<(h||1);b++){var s=h?g[b][a]:g[a],d=Math.round(s*p)||1,d=this.finger(v,c+o/2,d,o-1,false,z).attr({stroke:"none",fill:A[h?b:a]});h?r[b].push(d):r.push(d);d.x=v+Math.round(s*p);d.y=c+o/2;d.w=Math.round(s*p);d.h=o;d.value=+s;j.stacked?m.push(d):c+=o}if(j.stacked){b=
k.rect(v,m[0].y-m[0].h/2,q,o).attr(this.shim);i.push(b);b.bars=k.set();for(var w=0,f=m.length;f--;)m[f].toFront();for(var f=0,y=m.length;f<y;f++){var d=m[f],s=Math.round((w+d.value)*p),B=this.finger(v,d.y,s,o-1,false,z,1);b.bars.push(d);w&&d.attr({path:B});d.w=s;d.x=v+s;l.push(s=k.rect(v+w*p,d.y-d.h/2,d.value*p,o).attr(this.shim));s.bar=d;w+=d.value}c+=o}c+=u}i.toFront();c=x+u;if(!j.stacked)for(a=0;a<n;a++){for(b=0;b<(h||1);b++)s=k.rect(v,c,q,o).attr(this.shim),l.push(s),s.bar=h?r[b][a]:r[a],s.value=
s.bar.value,c+=o;c+=u}e.label=function(a,b){a=a||[];this.labels=k.set();for(var c=0;c<n;c++)for(var d=0;d<h;d++){var e=k.g.labelise(h?a[d]&&a[d][c]:a[c],h?g[d][c]:g[c],t),f=b?"end":"start";this.labels.push(e=k.g.text(b?r[c*(h||1)+d].x-o/2+3:v+5,r[c*(h||1)+d].y,e).attr({"text-anchor":f}).insertBefore(l[0]));e.getBBox().x<v+5?e.attr({x:v+5,"text-anchor":"start"}):r[c*(h||1)+d].label=e}return this};e.hover=function(a,b){i.hide();l.show();l.mouseover(a).mouseout(b||function(){});return this};e.hoverColumn=
function(a,b){l.hide();i.show();i.mouseover(a).mouseout(b||function(){});return this};e.each=function(a){if(!Raphael.is(a,"function"))return this;for(var b=l.length;b--;)a.call(l[b]);return this};e.eachColumn=function(a){if(!Raphael.is(a,"function"))return this;for(var b=i.length;b--;)a.call(i[b]);return this};e.click=function(a){i.hide();l.show();l.click(a);return this};e.clickColumn=function(a){l.hide();i.show();i.click(a);return this};e.push(r,l,i);e.bars=r;e.covers=l;return e};