/*!
 * g.Raphael 0.5 - Charting library, based on Raphaël
 *
 * Copyright (c) 2009 Dmitry Baranovskiy (http://g.raphaeljs.com)
 * Copyright (c) 2011 Karol Kowalski
 * Licensed under the MIT (http://www.opensource.org/licenses/mit-license.php) license.
 */
Raphael.fn.g.fn.dotchart=function(m,n,o,g,l,h,t,c){function C(a){+a[0]&&(a[0]=this.axis(m+b,n+b,o-2*b,p,z,c.axisxstep||Math.floor((o-2*b)/20),2,c.axisxlabels||null,c.axisxtype||"t"));+a[1]&&(a[1]=this.axis(m+o-b,n+g-b,g-2*b,q,A,c.axisystep||Math.floor((g-2*b)/20),3,c.axisylabels||null,c.axisytype||"t"));+a[2]&&(a[2]=this.axis(m+b,n+g-b+u,o-2*b,p,z,c.axisxstep||Math.floor((o-2*b)/20),0,c.axisxlabels||null,c.axisxtype||"t"));+a[3]&&(a[3]=this.axis(m+b-u,n+g-b,g-2*b,q,A,c.axisystep||Math.floor((g-2*
b)/20),1,c.axisylabels||null,c.axisytype||"t"))}for(var c=c||{},i=this.snapEnds(Math.min.apply(Math,l),Math.max.apply(Math,l),l.length-1),p=i.from,z=i.to,b=c.gutter||10,i=this.snapEnds(Math.min.apply(Math,h),Math.max.apply(Math,h),h.length-1),q=i.from,A=i.to,r=Math.max(l.length,h.length,t.length),i=this.markers[c.symbol]||"disc",j=this.paper.set(),v=this.paper.set(),B=c.max||100,a=Math.max.apply(Math,t),k=[],f=Math.sqrt(a/Math.PI)*2/B,a=0;a<r;a++)k[a]=Math.min(Math.sqrt(t[a]/Math.PI)*2/f,B);var b=
Math.max.apply(Math,k.concat(b)),r=this.paper.set(),u=Math.max.apply(Math,k);if(c.axis){var e=(c.axis+"").split(/[,\s]+/);C.call(this,e);for(var s=[],a=0,f=e.length;a<f;a++){var w=e[a].all?e[a].all.getBBox()[["height","width"][a%2]]:0;s[a]=w+b}b=Math.max.apply(Math,s.concat(b));a=0;for(f=e.length;a<f;a++)e[a].all&&(e[a].remove(),e[a]=1);C.call(this,e);a=0;for(f=e.length;a<f;a++)e[a].all&&r.push(e[a].all);j.axis=r}e=(o-b*2)/(z-p||1);s=(g-b*2)/(A-q||1);a=0;for(f=h.length;a<f;a++){var w=this.paper.raphael.is(i,
"array")?i[a]:i,x=m+b+(l[a]-p)*e,y=n+g-b-(h[a]-q)*s;w&&k[a]&&v.push(this[w](x,y,k[a]).attr({fill:c.heat?this.colorValue(k[a],u):Raphael.fn.g.colors[0],"fill-opacity":c.opacity?k[a]/B:1,stroke:"none"}))}for(var d=this.paper.set(),a=0,f=h.length;a<f;a++)x=m+b+(l[a]-p)*e,y=n+g-b-(h[a]-q)*s,d.push(this.paper.circle(x,y,u).attr(this.shim)),c.href&&c.href[a]&&d[a].attr({href:c.href[a]}),d[a].r=+k[a].toFixed(3),d[a].x=+x.toFixed(3),d[a].y=+y.toFixed(3),d[a].X=l[a],d[a].Y=h[a],d[a].value=t[a]||0,d[a].dot=
v[a];j.covers=d;j.series=v;j.push(v,r,d);j.hover=function(a,b){d.mouseover(a).mouseout(b);return this};j.click=function(a){d.click(a);return this};j.each=function(a){if(!Raphael.is(a,"function"))return this;for(var b=d.length;b--;)a.call(d[b]);return this};j.href=function(a){for(var b,c=d.length;c--;)b=d[c],b.X==a.x&&b.Y==a.y&&b.value==a.value&&b.attr({href:a.href})};return j};