/*!
 * g.Raphael 0.5 - Charting library, based on Raphaël
 *
 * Copyright (c) 2009 Dmitry Baranovskiy (http://g.raphaeljs.com)
 * Copyright (c) 2011 Karol Kowalski
 * Licensed under the MIT (http://www.opensource.org/licenses/mit-license.php) license.
 */
Raphael.fn.g.fn.piechart=function(q,r,j,d,c){var c=c||{},m=this.paper,s=this,w=[],n=m.set(),b=m.set(),g=m.set(),k=d.length,o=0,l=0,p=0,i=9,e=true;b.covers=n;if(k==1)g.push(m.circle(q,r,j).attr({fill:s.colors[0],stroke:c.stroke||"#fff","stroke-width":c.strokewidth==null?1:c.strokewidth})),n.push(m.circle(q,r,j).attr(s.shim)),l=d[0],d[0]={value:d[0],order:0,valueOf:function(){return this.value}},g[0].middle={x:q,y:r},g[0].mangle=180;else{for(var x=function(t,a,d,f,c){var b=Math.PI/180,h=t+d*Math.cos(-f*
b),e=t+d*Math.cos(-c*b),j=t+d/2*Math.cos(-(f+(c-f)/2)*b),g=a+d*Math.sin(-f*b),k=a+d*Math.sin(-c*b),b=a+d/2*Math.sin(-(f+(c-f)/2)*b),t=["M",t,a,"L",h,g,"A",d,d,0,+(Math.abs(c-f)>180),1,e,k,"z"];t.middle={x:j,y:b};return t},a=0;a<k;a++)l+=d[a],d[a]={value:d[a],order:a,valueOf:function(){return this.value}};d.sort(function(d,a){return a.value-d.value});for(a=0;a<k;a++)if(e&&d[a]*360/l<=1.5&&(i=a,e=false),a>i)e=false,d[i].value+=d[a],d[i].others=true,p=d[i].value;k=Math.min(i+1,d.length);p&&d.splice(k)&&
(d[i].others=true);for(a=0;a<k;a++){p=o-360*d[a]/l/2;a||(o=90-p,p=o-360*d[a]/l/2);if(c.init)var y=x(q,r,1,o,o-360*d[a]/l).join(",");i=x(q,r,j,o,o-=360*d[a]/l);e=m.path(c.init?y:i).attr({fill:c.colors&&c.colors[a]||s.colors[a]||"#666",stroke:c.stroke||"#fff","stroke-width":c.strokewidth==null?1:c.strokewidth,"stroke-linejoin":"round"});e.value=d[a];e.middle=i.middle;e.mangle=p;w.push(e);g.push(e);c.init&&e.animate({path:i.join(",")},+c.init-1||1E3,">")}for(a=0;a<k;a++)e=m.path(w[a].attr("path")).attr(s.shim),
c.href&&c.href[a]&&e.attr({href:c.href[a]}),e.attr=function(){},n.push(e),g.push(e)}b.hover=function(a,c){for(var c=c||function(){},b=this,f=0;f<k;f++)(function(f,e,h){var g={sector:f,cover:e,cx:q,cy:r,mx:f.middle.x,my:f.middle.y,mangle:f.mangle,r:j,value:d[h],total:l,label:b.labels&&b.labels[h]};e.mouseover(function(){a.call(g)}).mouseout(function(){c.call(g)})})(g[f],n[f],f);return this};b.each=function(a){for(var c=0;c<k;c++){var b=g[c];a.call({sector:b,cover:n[c],cx:q,cy:r,x:b.middle.x,y:b.middle.y,
mangle:b.mangle,r:j,value:d[c],total:l,label:this.labels&&this.labels[c]})}return this};b.click=function(a){for(var c=this,b=0;b<k;b++)(function(b,e,g){var h={sector:b,cover:e,cx:q,cy:r,mx:b.middle.x,my:b.middle.y,mangle:b.mangle,r:j,value:d[g],total:l,label:c.labels&&c.labels[g]};e.click(function(){a.call(h)})})(g[b],n[b],b);return this};b.inject=function(b){b.insertBefore(n[0])};c.legend&&function(a,e,i,f){var o=q+j+j/5,p=r+10,a=a||[],f=f&&f.toLowerCase&&f.toLowerCase()||"east",i=s.markers[i&&i.toLowerCase()]||
"disc";b.labels=m.set();for(var h=0;h<k;h++){var v=g[h].attr("fill"),u=d[h].order;d[h].others&&(a[u]=e||"Others");a[u]=s.labelise(a[u],d[h],l);b.labels.push(m.set());b.labels[h].push(s[i](o+5,p,5).attr({fill:v,stroke:"none"}));b.labels[h].push(v=m.text(o+20,p,a[u]||d[u]).attr(s.txtattr).attr({fill:c.legendcolor||"#000","text-anchor":"start"}));n[h].label=b.labels[h];p+=v.getBBox().height*1.2}a=b.labels.getBBox();b.labels.translate.apply(b.labels,{east:[0,-a.height/2],west:[-a.width-2*j-20,-a.height/
2],north:[-j-a.width/2,-j-a.height-10],south:[-j-a.width/2,j+10]}[f]);b.push(b.labels)}(c.legend,c.legendothers,c.legendmark,c.legendpos);b.push(g,n);b.series=g;b.covers=n;return b};